# Generated by Django 2.2.28 on 2026-03-23 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_spend', '0003_expensecategory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_spend.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('user', 'name')},
        ),
    ]
