# Generated by Django 2.2.28 on 2026-03-23 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_spend', '0004_auto_20260323_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='lastAddedTo',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
