# Generated by Django 2.2.28 on 2026-03-23 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_spend', '0005_expensecategory_lastaddedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='lastAddedTo',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
