# Generated by Django 2.2.28 on 2026-03-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_spend', '0006_auto_20260323_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberofgroup',
            name='paid_of',
            field=models.BooleanField(default=False),
        ),
    ]
