# Generated by Django 2.2.28 on 2026-03-25 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_spend', '0007_memberofgroup_paid_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 25, 17, 33, 5, 643382)),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='lastAddedTo',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
