# Generated by Django 2.2.28 on 2026-03-25 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_spend', '0008_auto_20260325_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberofgroup',
            name='lastPayment',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='group',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 25, 17, 34, 54, 327886)),
        ),
    ]
