# Generated by Django 2.2.28 on 2026-03-25 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_spend', '0009_auto_20260325_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
