# Generated by Django 2.2.28 on 2026-03-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_spend', '0010_auto_20260325_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='money_spent',
            new_name='money_per_user',
        ),
        migrations.RenameField(
            model_name='memberofgroup',
            old_name='paid_of',
            new_name='paid_off',
        ),
        migrations.AddField(
            model_name='group',
            name='numberOfUsers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='memberofgroup',
            name='money_spent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
