# Generated by Django 2.2.28 on 2026-03-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_spend', '0011_auto_20260325_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberofgroup',
            name='groupAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
