# Generated by Django 2.2.28 on 2026-03-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_spend', '0012_memberofgroup_groupadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
